# Generated by Django 5.1.3 on 2024-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='wet',
            field=models.PositiveSmallIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='plantname'),
        ),
    ]
