# Generated by Django 5.1.3 on 2024-12-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_api', '0002_alter_bed_wet_alter_plant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='last_watered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
