# Generated by Django 5.1.3 on 2024-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_api', '0005_plot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='image',
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
